---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v1.5.4"
    hooks:
      - id: autopep8
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint aoctools
        language: python
        pass_filenames: false
        stages: [commit]
